name: idkbro
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  device_info_plus: ^11.4.0
  flutter:
    sdk: flutter

  geolocator: ^14.0.0
  image_picker: ^1.1.2
  mobile_scanner: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
